# Test configuration for Personal Pipeline MCP Server
server:
  {
    "port": 3000,
    "host": "localhost",
    "log_level": "info",
    "cache_ttl_seconds": 3600,
    "max_concurrent_requests": 100,
    "request_timeout_ms": 30000,
    "health_check_interval_ms": 60000
  }

sources:
  [
    {
      "name": "test-runbooks",
      "type": "file",
      "base_url": "./test-data/runbooks",
      "refresh_interval": "1h",
      "priority": 1,
      "enabled": true,
      "timeout_ms": 5000,
      "max_retries": 2
    },
    {
      "name": "test-knowledge-base",
      "type": "file",
      "base_url": "./test-data/knowledge-base",
      "refresh_interval": "1h",
      "priority": 2,
      "enabled": true,
      "timeout_ms": 5000,
      "max_retries": 2
    }
  ]

embedding:
  {
    "enabled": true,
    "model": "sentence-transformers/all-MiniLM-L6-v2",
    "cache_size": 100
  }