# Personal Pipeline - Confluence Adapter Configuration
# 
# Enterprise-grade Confluence integration configuration
# Copy this file to config.yaml and customize for your environment

server:
  port: 3000
  host: "localhost"
  log_level: "info"
  cache_ttl_seconds: 3600
  max_concurrent_requests: 100
  request_timeout_ms: 30000
  health_check_interval_ms: 60000

# Source configurations
sources:
  # Confluence adapter with enterprise features
  - name: "enterprise-confluence"
    type: "confluence"
    # REQUIRED: Your Confluence instance URL
    base_url: "https://your-company.atlassian.net/wiki"
    
    # OPTIONAL: Limit to specific spaces (if not provided, all accessible spaces are indexed)
    space_keys:
      - "DOCS"        # Documentation space
      - "RUNBOOKS"    # Operational runbooks
      - "KB"          # Knowledge base
      - "DEVOPS"      # DevOps procedures
    
    # Authentication configuration
    auth:
      # Option 1: Bearer Token (recommended for service accounts)
      type: "bearer_token"
      token_env: "CONFLUENCE_TOKEN"  # Environment variable containing API token
      
      # Option 2: Basic Authentication (for username/password)
      # type: "basic"
      # username_env: "CONFLUENCE_USERNAME"
      # password_env: "CONFLUENCE_PASSWORD"
      
      # Option 3: OAuth 2.0 (for user authentication)
      # type: "oauth2"
      # oauth_config:
      #   client_id_env: "CONFLUENCE_OAUTH_CLIENT_ID"
      #   client_secret_env: "CONFLUENCE_OAUTH_CLIENT_SECRET"
      #   redirect_uri: "http://localhost:3000/auth/confluence/callback"

    # Synchronization settings
    refresh_interval: "1h"      # How often to sync content
    priority: 1                 # Source priority (1 = highest)
    enabled: true               # Enable/disable this source
    timeout_ms: 30000          # Request timeout
    max_retries: 3             # Maximum retry attempts

    # Confluence-specific settings
    rate_limit: 10             # Requests per second (respect Atlassian limits)
    max_results: 100           # Maximum results per query

  # Alternative Confluence configuration for different instance
  - name: "legacy-confluence"
    type: "confluence"
    base_url: "https://legacy.company.com/confluence"
    space_keys:
      - "LEGACY"
      - "ARCHIVE"
    auth:
      type: "basic"
      username_env: "LEGACY_CONFLUENCE_USERNAME"
      password_env: "LEGACY_CONFLUENCE_PASSWORD"
    refresh_interval: "4h"
    priority: 2
    enabled: false  # Disabled by default
    timeout_ms: 45000
    max_retries: 5
    rate_limit: 5    # Slower rate limit for legacy instance
    max_results: 50

# Cache configuration for optimal performance
cache:
  enabled: true
  strategy: "hybrid"  # memory_only, redis_only, or hybrid
  
  # Memory cache settings
  memory:
    max_keys: 2000
    ttl_seconds: 3600
    check_period_seconds: 600
  
  # Redis cache settings (for production environments)
  redis:
    enabled: true
    url: "redis://localhost:6379"
    ttl_seconds: 7200
    key_prefix: "pp:confluence:"
    connection_timeout_ms: 5000
    retry_attempts: 3
    retry_delay_ms: 1000
    max_retry_delay_ms: 30000
    backoff_multiplier: 2
    connection_retry_limit: 5
  
  # Content-specific cache TTLs
  content_types:
    runbooks:
      ttl_seconds: 3600     # 1 hour for runbooks
      warmup: true          # Pre-load critical runbooks
    procedures:
      ttl_seconds: 1800     # 30 minutes for procedures
      warmup: false
    decision_trees:
      ttl_seconds: 2400     # 40 minutes for decision trees
      warmup: true
    knowledge_base:
      ttl_seconds: 900      # 15 minutes for general knowledge
      warmup: false

# Semantic search configuration
semantic_search:
  enabled: true
  model: "Xenova/all-MiniLM-L6-v2"
  max_cache_size: 10000
  min_similarity_threshold: 0.3
  enhance_existing_adapters: true
  fallback_to_fuzzy: true
  
  # Scoring weights for hybrid search
  scoring_weights:
    semantic: 0.6    # Semantic similarity weight
    fuzzy: 0.3       # Fuzzy search weight  
    metadata: 0.1    # Metadata relevance weight
  
  # Performance settings
  performance:
    batch_size: 32
    enable_caching: true
    warmup_cache: true
    max_response_time_ms: 200

---
# Environment Variables Required:
# 
# For Bearer Token Authentication:
# CONFLUENCE_TOKEN=your_confluence_api_token
# 
# For Basic Authentication:
# CONFLUENCE_USERNAME=your_username
# CONFLUENCE_PASSWORD=your_password
# 
# For OAuth 2.0:
# CONFLUENCE_OAUTH_CLIENT_ID=your_client_id
# CONFLUENCE_OAUTH_CLIENT_SECRET=your_client_secret
# 
# For Redis Cache:
# REDIS_URL=redis://localhost:6379
# 
# Example .env file:
# CONFLUENCE_TOKEN=ATATT3xFfGF0...your_token_here
# REDIS_URL=redis://localhost:6379
# LOG_LEVEL=info

---
# Setup Instructions:
# 
# 1. Create Confluence API Token:
#    - Go to https://id.atlassian.com/manage-profile/security/api-tokens
#    - Create a new API token
#    - Copy the token and set CONFLUENCE_TOKEN environment variable
# 
# 2. Configure Spaces:
#    - Update space_keys to match your Confluence spaces
#    - Use space keys (e.g., "DOCS") not space names
#    - Leave empty array [] to index all accessible spaces
# 
# 3. Test Configuration:
#    npm run health
#    npm run demo:start
# 
# 4. Performance Tuning:
#    - Adjust rate_limit based on your Confluence plan
#    - Tune cache TTLs based on content update frequency
#    - Set appropriate max_results for your use case
# 
# 5. Enterprise Deployment:
#    - Use Redis for production caching
#    - Configure appropriate refresh_interval
#    - Monitor rate limits and adjust accordingly
#    - Enable semantic search for enhanced relevance