server:
  port: 3000
  host: localhost
  log_level: info
  cache_ttl_seconds: 3600
  max_concurrent_requests: 100
  request_timeout_ms: 30000
  health_check_interval_ms: 60000
sources:
  - name: confluence-ops
    type: confluence
    base_url: https://your-company.atlassian.net/wiki
    auth:
      type: bearer_token
      token_env: CONFLUENCE_TOKEN
    refresh_interval: 1h
    priority: 1
    enabled: true
    timeout_ms: 30000
    max_retries: 3
  - name: github-docs
    type: github
    base_url: https://api.github.com/repos/your-org/docs
    auth:
      type: bearer_token
      token_env: GITHUB_TOKEN
    refresh_interval: 30m
    priority: 2
    enabled: true
    timeout_ms: 15000
    max_retries: 2
  - name: local-runbooks
    type: file
    base_url: ./runbooks
    refresh_interval: 5m
    priority: 3
    enabled: true
    timeout_ms: 5000
    max_retries: 1
embedding:
  enabled: true
  model: sentence-transformers/all-MiniLM-L6-v2
  cache_size: 1000
