server:
  port: 3000
  host: localhost
  log_level: info
  cache_ttl_seconds: 3600
  max_concurrent_requests: 100
  request_timeout_ms: 30000
  health_check_interval_ms: 60000
sources:
  - name: local-runbooks
    type: file
    base_url: ./runbooks
    refresh_interval: 5m
    priority: 1
    enabled: true
    timeout_ms: 5000
    max_retries: 1
  - name: company-wiki
    type: web
    base_url: https://wiki.company.com/api/v1/pages
    auth:
      type: bearer_token
      token_env: WIKI_API_TOKEN
    refresh_interval: 30m
    priority: 2
    enabled: false                     # Disabled by default - enable only when needed to avoid external HTTP calls during testing
    timeout_ms: 15000
    max_retries: 2
    # Enhanced FileSystem Adapter features
    watch_changes: true              # Monitor file changes for real-time updates
    pdf_extraction: true             # Extract text from PDF files
    recursive: true                  # Scan subdirectories recursively
    max_depth: 5                     # Maximum directory depth to scan
    extract_metadata: true           # Extract file metadata (author, tags, etc.)
    supported_extensions: ['.md', '.txt', '.json', '.yml', '.yaml', '.pdf', '.rst', '.adoc']
    file_patterns:
      include: []                    # Optional: specific patterns to include
      exclude: ['**/node_modules/**', '**/.git/**']  # Patterns to exclude
# Caching Configuration
# Personal Pipeline supports flexible caching strategies with automatic fallback
cache:
  enabled: true                    # Enable/disable caching entirely
  strategy: hybrid                 # Options: hybrid, memory_only
                                  # - hybrid: Memory + Redis (recommended)
                                  # - memory_only: Memory cache only
  
  # In-Memory Cache Settings (always enabled)
  memory:
    max_keys: 1000                 # Maximum number of cached items
    ttl_seconds: 3600              # Default TTL (1 hour)
    check_period_seconds: 600      # Cleanup interval (10 minutes)
  
  # Redis Cache Settings (optional external dependency)
  # Redis is DISABLED by default. Enable by setting REDIS_URL env var or enabled: true
  # System uses memory-only caching unless Redis is explicitly configured
  redis:
    enabled: false                 # Enable Redis caching (set to true or use REDIS_URL env var)
    url: redis://localhost:6379    # Redis connection URL (or use REDIS_URL environment variable)
                                  # Supports: redis://host:port, rediss://host:port (SSL)
                                  # With auth: redis://user:pass@host:port
    ttl_seconds: 7200              # Redis TTL (2 hours, longer than memory)
    key_prefix: 'pp:cache:'        # Namespace for Personal Pipeline keys
    
    # Connection Management
    connection_timeout_ms: 5000    # Initial connection timeout
    retry_attempts: 3              # Number of retry attempts
    retry_delay_ms: 2000           # Start with 2 second delay
    
    # Exponential backoff settings for production resilience
    max_retry_delay_ms: 120000     # Max 2 minutes between retries
    backoff_multiplier: 2.5        # Exponential backoff factor
    connection_retry_limit: 5      # Max attempts before circuit breaker activation
  # Content-Specific Cache Settings
  # Different content types can have different TTL and warmup strategies
  content_types:
    runbooks:                      # Critical operational runbooks
      ttl_seconds: 3600            # Cache for 1 hour (frequently accessed)
      warmup: true                 # Pre-load into cache on startup
    procedures:                    # Step-by-step procedures
      ttl_seconds: 1800            # Cache for 30 minutes (moderate access)
      warmup: false                # Load on-demand
    decision_trees:                # Decision logic trees
      ttl_seconds: 2400            # Cache for 40 minutes (important but stable)
      warmup: true                 # Pre-load for faster incident response
    knowledge_base:                # General knowledge articles
      ttl_seconds: 900             # Cache for 15 minutes (less critical)
      warmup: false                # Load on-demand to save memory
embedding:
  enabled: true
  model: sentence-transformers/all-MiniLM-L6-v2
  cache_size: 1000
