# Database Adapter Configuration Examples
# 
# This file provides sample configurations for the Database adapter
# supporting multiple database types with comprehensive documentation.

# PostgreSQL Configuration
postgresql_example:
  server:
    port: 3000
    host: localhost
    log_level: info
  
  sources:
    - name: "postgresql-knowledge-base"
      type: "database"
      connection:
        type: "postgresql"
        host: "localhost"
        port: 5432
        database: "knowledge_base"
        username_env: "POSTGRES_USER"      # Environment variable name
        password_env: "POSTGRES_PASSWORD"  # Environment variable name
        ssl: true
        ssl_cert_path: "/path/to/client-cert.pem"
        ssl_key_path: "/path/to/client-key.pem"
        ssl_ca_path: "/path/to/ca-cert.pem"
        pool_size: 20
        connection_timeout_ms: 30000
        idle_timeout_ms: 300000
        max_lifetime_ms: 1800000
      
      schema:
        tables:
          - name: "documentation"
            title_field: "title"
            content_field: "content"
            category_field: "category"
            updated_field: "updated_at"
            author_field: "author"
            tags_field: "tags"
            type: "documentation"
            filters:
              published: true  # Additional WHERE condition
          
          - name: "runbooks"
            title_field: "name"
            content_field: "procedure"
            category_field: "severity"
            updated_field: "last_modified"
            author_field: "created_by"
            type: "runbook"
          
          - name: "procedures"
            title_field: "procedure_name"
            content_field: "steps"
            category_field: "department"
            type: "procedure"
          
          - name: "faqs"
            title_field: "question"
            content_field: "answer"
            category_field: "topic"
            type: "faq"
      
      performance:
        query_timeout_ms: 15000
        max_concurrent_queries: 25
        cache_ttl_seconds: 3600
        enable_query_optimization: true
      
      refresh_interval: "30m"
      priority: 1
      enabled: true
      timeout_ms: 30000
      max_retries: 3

# MongoDB Configuration
mongodb_example:
  server:
    port: 3000
    host: localhost
    log_level: info
  
  sources:
    - name: "mongodb-document-store"
      type: "database"
      connection:
        type: "mongodb"
        database: "documentation"
        uri_env: "MONGODB_URI"  # mongodb://username:password@host:port/database
        ssl: true
        pool_size: 30
        connection_timeout_ms: 30000
        idle_timeout_ms: 300000
        max_lifetime_ms: 1800000
      
      schema:
        collections:
          - name: "articles"
            title_field: "title"
            content_field: "body"
            category_field: "category"
            updated_field: "updatedAt"
            type: "documentation"
          
          - name: "incident_procedures"
            title_field: "title"
            content_field: "steps"
            category_field: "severity"
            type: "runbook"
          
          - name: "knowledge_base"
            title_field: "question"
            content_field: "answer"
            category_field: "topic"
            type: "faq"
      
      refresh_interval: "1h"
      priority: 2
      enabled: true

# MySQL Configuration
mysql_example:
  server:
    port: 3000
    host: localhost
    log_level: info
  
  sources:
    - name: "mysql-documentation"
      type: "database"
      connection:
        type: "mysql"
        host: "mysql.company.com"
        port: 3306
        database: "docs"
        username_env: "MYSQL_USER"
        password_env: "MYSQL_PASSWORD"
        ssl: true
        pool_size: 15
        connection_timeout_ms: 30000
        idle_timeout_ms: 300000
        max_lifetime_ms: 1800000
      
      schema:
        tables:
          - name: "wiki_pages"
            title_field: "page_title"
            content_field: "page_content"
            category_field: "namespace"
            updated_field: "last_updated"
            author_field: "last_editor"
            type: "documentation"
          
          - name: "troubleshooting_guides"
            title_field: "issue_title"
            content_field: "resolution_steps"
            category_field: "component"
            type: "procedure"
      
      refresh_interval: "2h"
      priority: 3
      enabled: true

# SQLite Configuration (for development/testing)
sqlite_example:
  server:
    port: 3000
    host: localhost
    log_level: debug
  
  sources:
    - name: "sqlite-local-docs"
      type: "database"
      connection:
        type: "sqlite"
        database: "/path/to/database.db"
        ssl: false
        pool_size: 1  # SQLite is single-threaded
        connection_timeout_ms: 30000
        idle_timeout_ms: 300000
        max_lifetime_ms: 1800000
      
      schema:
        tables:
          - name: "local_docs"
            title_field: "title"
            content_field: "content"
            category_field: "type"
            updated_field: "modified"
            type: "documentation"
      
      refresh_interval: "5m"
      priority: 4
      enabled: true

# Microsoft SQL Server Configuration
mssql_example:
  server:
    port: 3000
    host: localhost
    log_level: info
  
  sources:
    - name: "sqlserver-enterprise-docs"
      type: "database"
      connection:
        type: "mssql"
        host: "sqlserver.company.com"
        port: 1433
        database: "EnterpriseKB"
        username_env: "MSSQL_USER"
        password_env: "MSSQL_PASSWORD"
        ssl: true
        pool_size: 20
        connection_timeout_ms: 30000
        idle_timeout_ms: 300000
        max_lifetime_ms: 1800000
      
      schema:
        tables:
          - name: "KnowledgeArticles"
            title_field: "Title"
            content_field: "Content"
            category_field: "Category"
            updated_field: "LastModified"
            author_field: "Author"
            type: "documentation"
          
          - name: "IncidentProcedures"
            title_field: "ProcedureName"
            content_field: "Steps"
            category_field: "Severity"
            type: "runbook"
      
      refresh_interval: "1h"
      priority: 1
      enabled: true

# Oracle Database Configuration
oracle_example:
  server:
    port: 3000
    host: localhost
    log_level: info
  
  sources:
    - name: "oracle-enterprise-kb"
      type: "database"
      connection:
        type: "oracle"
        host: "oracle.company.com"
        port: 1521
        database: "XE"  # Service name
        username_env: "ORACLE_USER"
        password_env: "ORACLE_PASSWORD"
        ssl: true
        pool_size: 25
        connection_timeout_ms: 30000
        idle_timeout_ms: 300000
        max_lifetime_ms: 1800000
      
      schema:
        tables:
          - name: "DOCUMENTATION"
            title_field: "TITLE"
            content_field: "CONTENT"
            category_field: "CATEGORY"
            updated_field: "UPDATED_DATE"
            type: "documentation"
      
      refresh_interval: "30m"
      priority: 1
      enabled: true

# Multi-Database Configuration
multi_database_example:
  server:
    port: 3000
    host: localhost
    log_level: info
  
  # Cache configuration for optimal performance
  cache:
    enabled: true
    strategy: "hybrid"  # memory_only, redis_only, or hybrid
    memory:
      max_keys: 10000
      ttl_seconds: 3600
    redis:
      enabled: true
      url: "redis://localhost:6379"
      ttl_seconds: 7200
      key_prefix: "pp:db_cache:"
  
  sources:
    # Primary documentation database
    - name: "primary-postgres-kb"
      type: "database"
      connection:
        type: "postgresql"
        host: "postgres-primary.company.com"
        port: 5432
        database: "knowledge_base"
        username_env: "POSTGRES_USER"
        password_env: "POSTGRES_PASSWORD"
        ssl: true
        pool_size: 30
      schema:
        tables:
          - name: "runbooks"
            title_field: "title"
            content_field: "content"
            category_field: "severity"
            type: "runbook"
          - name: "procedures"
            title_field: "name"
            content_field: "steps"
            type: "procedure"
      priority: 1
      refresh_interval: "15m"
      enabled: true
    
    # Legacy MySQL documentation
    - name: "legacy-mysql-docs"
      type: "database"
      connection:
        type: "mysql"
        host: "mysql-legacy.company.com"
        port: 3306
        database: "legacy_docs"
        username_env: "MYSQL_USER"
        password_env: "MYSQL_PASSWORD"
        ssl: true
        pool_size: 10
      schema:
        tables:
          - name: "old_documentation"
            title_field: "doc_title"
            content_field: "doc_content"
            category_field: "doc_type"
            type: "documentation"
      priority: 2
      refresh_interval: "2h"
      enabled: true
    
    # MongoDB for modern content
    - name: "modern-mongodb-content"
      type: "database"
      connection:
        type: "mongodb"
        database: "modern_kb"
        uri_env: "MONGODB_URI"
        ssl: true
        pool_size: 20
      schema:
        collections:
          - name: "articles"
            title_field: "title"
            content_field: "content"
            type: "documentation"
          - name: "faqs"
            title_field: "question"
            content_field: "answer"
            type: "faq"
      priority: 1
      refresh_interval: "30m"
      enabled: true

# Environment Variables Required:
# 
# For PostgreSQL:
# - POSTGRES_USER=your_username
# - POSTGRES_PASSWORD=your_password
#
# For MongoDB:
# - MONGODB_URI=mongodb://username:password@host:port/database
#
# For MySQL:
# - MYSQL_USER=your_username
# - MYSQL_PASSWORD=your_password
#
# For SQL Server:
# - MSSQL_USER=your_username
# - MSSQL_PASSWORD=your_password
#
# For Oracle:
# - ORACLE_USER=your_username
# - ORACLE_PASSWORD=your_password

# Performance Tuning Guidelines:
#
# 1. Connection Pool Sizing:
#    - PostgreSQL/MySQL: 10-30 connections
#    - MongoDB: 20-50 connections
#    - SQLite: 1 connection (single-threaded)
#
# 2. Query Optimization:
#    - Enable query optimization for better performance
#    - Use appropriate indexes on title and content fields
#    - Consider partitioning large tables
#
# 3. Caching Strategy:
#    - Use hybrid caching for best performance
#    - Adjust TTL based on data update frequency
#    - Monitor cache hit rates and adjust accordingly
#
# 4. Schema Design:
#    - Ensure proper field mapping for optimal search
#    - Use appropriate data types for content fields
#    - Consider denormalization for read-heavy workloads