# GitHub Adapter Sample Configuration
# 
# This configuration demonstrates responsible GitHub API usage
# with conservative defaults and explicit user consent requirements.
#
# Copy this file to your main config.yaml and uncomment the sources
# section to enable GitHub integration.

server:
  port: 3000
  host: "localhost"
  log_level: "info"
  cache_ttl_seconds: 3600
  max_concurrent_requests: 100
  request_timeout_ms: 30000
  health_check_interval_ms: 60000

# Uncomment and configure the sources section to enable GitHub integration
# sources:
#   - name: "github-docs"
#     type: "github"
#     enabled: true
#     
#     # GitHub Authentication (REQUIRED)
#     auth:
#       type: "personal_token"
#       token_env: "GITHUB_TOKEN"  # Set this environment variable
#     
#     # Repository Scope (EXPLICIT REPOSITORIES ONLY - NO AUTO-DISCOVERY)
#     scope:
#       # Specify exact repositories to index - NO wildcards or auto-discovery
#       repositories:
#         - "your-org/documentation"
#         - "your-org/runbooks"
#         - "your-org/operational-guides"
#       
#       # Organization scanning DISABLED by default - requires explicit opt-in
#       # organizations: []
#       # user_consent_given: false  # MUST be set to true for org scanning
#       
#       # Private repository access (disabled by default)
#       include_private: false
#       
#       # Repository filters (only used with organization scanning)
#       # repository_filters:
#       #   topics: ["documentation", "runbooks", "ops"]
#       #   languages: ["markdown"]
#       #   min_stars: 1
#       #   max_age_days: 365
#     
#     # Content Types (Conservative defaults)
#     content_types:
#       readme: true               # Index README files
#       wiki: false                # Disabled by default (high API usage)
#       documentation: true        # Index docs/ directories
#       issues: false              # Disabled by default (high API usage)
#       pull_requests: false       # Disabled by default (high API usage)
#       code_comments: false       # Disabled by default (high API usage)
#     
#     # Performance Settings (HIGHLY CONSERVATIVE)
#     performance:
#       cache_ttl: "4h"                    # Long cache duration (4 hours)
#       max_file_size_kb: 100              # Skip large files (100KB limit)
#       rate_limit_quota: 10               # Use only 10% of GitHub's rate limit
#       min_request_interval_ms: 2000      # Minimum 2 seconds between requests
#       concurrent_requests: 1             # Serial requests only
#       max_repositories_per_scan: 3       # Maximum 3 repositories per operation
#     
#     # Refresh settings
#     refresh_interval: "6h"               # Refresh every 6 hours
#     timeout_ms: 30000
#     max_retries: 2
#     priority: 1
#     
#     # Categories for filtering
#     categories: ["documentation", "runbooks", "operational"]

# Example of organization scanning (REQUIRES EXPLICIT ENABLEMENT)
# sources:
#   - name: "github-org-scan"
#     type: "github"
#     enabled: false  # DISABLED by default - must be explicitly enabled
#     
#     auth:
#       type: "personal_token"
#       token_env: "GITHUB_ORG_TOKEN"
#     
#     scope:
#       # EXPLICIT CONSENT REQUIRED for organization scanning
#       organizations: ["your-org"]
#       user_consent_given: true  # MUST be explicitly set
#       
#       # REQUIRED: Repository filters to limit scope
#       repository_filters:
#         topics: ["documentation", "runbooks", "ops"]
#         languages: ["markdown"]
#         min_stars: 1
#         max_age_days: 365
#     
#     content_types:
#       readme: true
#       documentation: true
#       wiki: false
#       issues: false
#       pull_requests: false
#       code_comments: false
#     
#     performance:
#       cache_ttl: "6h"                    # Longer cache for org scanning
#       rate_limit_quota: 25               # Higher quota for org scanning
#       max_repositories_per_scan: 10      # More repos for org scanning
#       concurrent_requests: 2             # Slight parallelism allowed
#       min_request_interval_ms: 1500      # Faster intervals for org scanning
#     
#     refresh_interval: "12h"              # Less frequent refresh
#     priority: 2

# Cache configuration
cache:
  enabled: true
  strategy: "hybrid"
  memory:
    max_keys: 1000
    ttl_seconds: 3600
    check_period_seconds: 600
  redis:
    enabled: true
    url: "redis://localhost:6379"
    ttl_seconds: 7200
    key_prefix: "pp:cache:"
    connection_timeout_ms: 5000
    retry_attempts: 3
    retry_delay_ms: 1000
  content_types:
    runbooks:
      ttl_seconds: 3600
      warmup: true
    procedures:
      ttl_seconds: 1800
      warmup: false
    decision_trees:
      ttl_seconds: 2400
      warmup: true
    knowledge_base:
      ttl_seconds: 900
      warmup: false

# Environment Variables Required:
# GITHUB_TOKEN=ghp_xxxxxxxxxxxxxxxxxxxx  (Personal Access Token with repo scope)
# 
# Optional for GitHub Apps:
# GITHUB_APP_ID=123456
# GITHUB_APP_PRIVATE_KEY_PATH=/path/to/private-key.pem
# GITHUB_INSTALLATION_ID=987654
# 
# Optional for webhooks:
# GITHUB_WEBHOOK_SECRET=your-webhook-secret

# Personal Access Token Scopes Required:
# - repo (for private repositories)
# - read:org (for organization repositories)
# - read:user (for authentication verification)
# 
# For public repositories only:
# - public_repo (minimal scope)

# API Usage Estimates:
# - 3 repositories with README + docs: ~21 API calls per refresh
# - Organization with 10 filtered repos: ~70 API calls per refresh
# - Conservative rate limit (10%): 500 requests/hour maximum
# - Typical usage: 50-100 requests/hour for 3-5 repositories

# Security Notes:
# - Never commit GitHub tokens to version control
# - Use environment variables for all credentials
# - Regularly rotate Personal Access Tokens
# - Monitor API usage through GitHub settings
# - Enable two-factor authentication on GitHub account