# Web Adapter Sample Configuration
# Enterprise-grade web documentation access configuration

# ============================================================================
# Web Adapter Configuration - Multi-Source Web Documentation Access
# ============================================================================

sources:
  # REST API Documentation Source
  - name: "api-docs"
    type: "web"
    priority: 1
    
    # Web-specific configuration
    sources:
      - name: "company-api"
        type: "api"
        base_url: "https://api.docs.company.com"
        
        endpoints:
          - name: "search"
            path: "/v1/search"
            method: "GET"
            content_type: "json"
            json_paths:
              - "$.results[*].title"
              - "$.results[*].content"
              - "$.results[*].url"
            query_params:
              format: "json"
              limit: "20"
            cache_ttl: "10m"
            
          - name: "documents"
            path: "/v1/documents/{id}"
            method: "GET"
            content_type: "json"
            cache_ttl: "1h"
            
        health_check:
          enabled: true
          endpoint: "/v1/health"
          interval_minutes: 5
          timeout_ms: 5000
    
    # Authentication configuration (API Key)
    auth:
      type: "api_key"
      api_key:
        location: "header"
        name: "X-API-Key"
        env_var: "COMPANY_API_KEY"
    
    # Performance settings
    performance:
      default_timeout_ms: 15000
      max_concurrent_requests: 5
      default_retry_attempts: 2
      default_cache_ttl: "5m"
      user_agent: "PersonalPipeline-Docs/1.0"
    
    # Content processing
    content_processing:
      max_content_size_mb: 5
      follow_redirects: true
      validate_ssl: true
      extract_links: false
      respect_robots: true
    
    # Rate limiting
    rate_limiting:
      global_requests_per_minute: 100
      per_source_requests_per_minute: 30
      burst_allowance: 10

  # Web Scraping Documentation Source
  - name: "docs-site"
    type: "web"
    priority: 2
    
    # Web scraping configuration
    sources:
      - name: "company-docs"
        type: "scraping"
        base_url: "https://docs.company.com"
        
        endpoints:
          - name: "search"
            path: "/search"
            method: "GET"
            content_type: "html"
            selectors:
              title: "h1.page-title"
              content: ".documentation-content"
              metadata: ".page-metadata"
              exclude:
                - ".navigation"
                - ".sidebar"
                - ".footer"
            query_params:
              q: "${query}"
            filters:
              min_content_length: 100
              exclude_patterns:
                - ".*cookie.*policy.*"
                - ".*privacy.*notice.*"
            cache_ttl: "30m"
            
          - name: "articles"
            path: "/articles/{id}"
            method: "GET"
            content_type: "html"
            selectors:
              title: "h1.article-title"
              content: ".article-body"
              date: ".publish-date"
              author: ".author-name"
            cache_ttl: "2h"
            
        health_check:
          enabled: true
          interval_minutes: 15
          timeout_ms: 10000
    
    # No authentication required for public docs
    auth:
      type: "none"
    
    # Conservative performance for scraping
    performance:
      default_timeout_ms: 30000
      max_concurrent_requests: 2
      default_retry_attempts: 3
      default_cache_ttl: "15m"
      user_agent: "PersonalPipeline-Scraper/1.0 (Respectful Bot)"
    
    # Respectful scraping settings
    content_processing:
      max_content_size_mb: 2
      follow_redirects: true
      validate_ssl: true
      extract_links: true
      respect_robots: true
    
    # Conservative rate limiting
    rate_limiting:
      global_requests_per_minute: 30
      per_source_requests_per_minute: 10
      burst_allowance: 3

  # RSS Feed Source
  - name: "news-feed"
    type: "web"
    priority: 3
    
    # RSS feed configuration
    sources:
      - name: "company-blog"
        type: "rss"
        base_url: "https://blog.company.com"
        
        endpoints:
          - name: "feed"
            path: "/feed.xml"
            method: "GET"
            content_type: "rss"
            cache_ttl: "1h"
            
          - name: "category-feed"
            path: "/category/{category}/feed.xml"
            method: "GET"
            content_type: "rss"
            cache_ttl: "2h"
            
        health_check:
          enabled: true
          interval_minutes: 30
          timeout_ms: 15000
    
    # No authentication for public feeds
    auth:
      type: "none"
    
    # Standard performance for feeds
    performance:
      default_timeout_ms: 20000
      max_concurrent_requests: 3
      default_retry_attempts: 2
      default_cache_ttl: "30m"
      user_agent: "PersonalPipeline-RSS/1.0"
    
    # RSS-specific settings
    content_processing:
      max_content_size_mb: 1
      follow_redirects: true
      validate_ssl: true
      extract_links: true
      respect_robots: false  # RSS feeds typically don't need robots.txt check
    
    # Gentle rate limiting for feeds
    rate_limiting:
      global_requests_per_minute: 20
      per_source_requests_per_minute: 5
      burst_allowance: 2

# ============================================================================
# OAuth 2.0 Example Configuration
# ============================================================================

# Uncomment and configure for OAuth 2.0 protected APIs
# sources:
#   - name: "oauth-api"
#     type: "web"
#     priority: 1
#     
#     sources:
#       - name: "secure-api"
#         type: "api"
#         base_url: "https://api.secure.company.com"
#         
#         endpoints:
#           - name: "search"
#             path: "/v2/search"
#             method: "POST"
#             content_type: "json"
#             body_template: '{"query": "${query}", "type": "documentation"}'
#             json_paths:
#               - "$.data[*].title"
#               - "$.data[*].content"
#               - "$.data[*].metadata"
#         
#         health_check:
#           enabled: true
#           endpoint: "/v2/health"
#           interval_minutes: 10
#           timeout_ms: 5000
#     
#     # OAuth 2.0 authentication
#     auth:
#       type: "oauth2"
#       oauth2:
#         client_id_env: "OAUTH_CLIENT_ID"
#         client_secret_env: "OAUTH_CLIENT_SECRET"
#         token_endpoint: "https://auth.company.com/oauth/token"
#         scope: "docs:read"
#         grant_type: "client_credentials"

# ============================================================================
# Environment Variables Required
# ============================================================================

# For API Key authentication:
# export COMPANY_API_KEY="your-api-key-here"

# For OAuth 2.0 authentication:
# export OAUTH_CLIENT_ID="your-client-id"
# export OAUTH_CLIENT_SECRET="your-client-secret"

# For Basic authentication:
# export API_USERNAME="your-username"
# export API_PASSWORD="your-password"

# For Bearer token authentication:
# export BEARER_TOKEN="your-bearer-token"

# ============================================================================
# Advanced Configuration Examples
# ============================================================================

# Custom headers and authentication:
# auth:
#   type: "custom"
#   custom:
#     headers:
#       "X-Custom-Auth": "static-value"
#     header_envs:
#       "Authorization": "CUSTOM_AUTH_TOKEN"
#       "X-Client-ID": "CLIENT_ID_ENV_VAR"

# Pagination support:
# endpoints:
#   - name: "paginated-search"
#     path: "/search"
#     method: "GET"
#     pagination:
#       type: "page_number"
#       page_param: "page"
#       size_param: "per_page"
#       max_pages: 10

# Content filtering:
# filters:
#   include_patterns:
#     - ".*runbook.*"
#     - ".*procedure.*"
#   exclude_patterns:
#     - ".*deprecated.*"
#   min_content_length: 200
#   max_content_length: 50000
#   required_elements:
#     - ".content-body"
#     - "h1"